# Generated by Django 5.2.7 on 2025-12-23 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landlords', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordfavoriteproperty',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landlordprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landlordfavoriteproperty',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landlords.landlordprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='landlordfavoriteproperty',
            unique_together={('landlord', 'property')},
        ),
    ]
