# Generated by Django 5.2.7 on 2025-12-16 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandlordFavoriteProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landlords.landlordprofile')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
            options={
                'unique_together': {('landlord', 'property')},
            },
        ),
    ]
