# Generated by Django 5.2.7 on 2025-12-14 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landlords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_type', models.CharField(choices=[('single', 'Single Room'), ('bedsitter', 'Bedsitter'), ('1BR', 'One Bedroom'), ('2BR', 'Two Bedroom'), ('3BR', 'Three Bedroom'), ('shared', 'Shared Unit')], max_length=50)),
                ('house_number', models.CharField(max_length=20)),
                ('rent', models.IntegerField()),
                ('county', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landlords.landlordprofile')),
            ],
            options={
                'permissions': [('can_add_property', 'Can add property'), ('can_edit_property', 'Can edit any property'), ('can_delete_property', 'Can delete property')],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_photos/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
        ),
    ]
