"""
Django settings for TafutaHao project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x&lgn5o0d^folzp6r*y#bjo@#9$zh%x2f$6yc#ktn7+tx@6gf@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1"] # Local development

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'landlords',
    'properties',
    'tenants',
    'csp'
]

AUTH_USER_MODEL = 'accounts.CustomUser'

# Redirect after logout
LOGOUT_REDIRECT_URL = '/'  # home page after logout

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware', # Security enhancements
    'csp.middleware.CSPMiddleware', # Content Security Policy middleware
    'django.contrib.sessions.middleware.SessionMiddleware', # Session management
    'django.middleware.common.CommonMiddleware', # Common HTTP features
    'django.middleware.csrf.CsrfViewMiddleware', # CSRF protection
    'django.contrib.auth.middleware.AuthenticationMiddleware', # Authentication
    'django.contrib.messages.middleware.MessageMiddleware', # Messaging framework
    'django.middleware.clickjacking.XFrameOptionsMiddleware', # Clickjacking protection (X-Frame-Options)
]

ROOT_URLCONF = 'TafutaHao.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TafutaHao.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'TafutaHao',
        'HOST' : 'localhost',
        'USER' : 'root',
        'PASSWORD' : 'Root@123',
        'PORT' : '3307'
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Prevent browser from guessing content types
SECURE_CONTENT_TYPE_NOSNIFF = True

# Clickjacking protection
X_FRAME_OPTIONS = "DENY"

# Enable browser XSS filtering
SECURE_BROWSER_XSS_FILTER = True  

# Prevent JavaScript access to session cookies
SESSION_COOKIE_HTTPONLY = True

# CSRF cookie not accessible via JS
CSRF_COOKIE_HTTPONLY = True

# SameSite policy
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

USE_HTTPS = False  # <-- KEEP FALSE for localhost

# Only enable these if HTTPS is actually available
SESSION_COOKIE_SECURE = USE_HTTPS
CSRF_COOKIE_SECURE = USE_HTTPS

# Redirect HTTP → HTTPS (DISABLED for localhost)
SECURE_SSL_REDIRECT = USE_HTTPS

SECURE_HSTS_SECONDS = 0  # MUST be 0 for localhost
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False

CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1",
    "http://localhost",
]

# Full CSP configuration
CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "default-src": ("'self'",),
        "script-src": (
            "'self'",
            "'unsafe-inline'",  # for dev only
            "'unsafe-eval'",    # for dev tools
        ),
        "style-src": (
            "'self'",
            "'unsafe-inline'",
        ),
        "img-src": (
            "'self'",
            "data:",
        ),
        "font-src": (
            "'self'",
            "data:",
        ),
        "connect-src": (
            "'self'",
        ),
        "frame-ancestors": ("'none'",),
        "object-src": ("'none'",),
    }
}
